/*
 * This file is part of Insight CAE, a workbench for Computer-Aided Engineering
 * Copyright (C) 2014  Hannes Kroeger <hannes@kroegeronline.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

#ifndef INSIGHT_OFMISCUTILS_H
#define INSIGHT_OFMISCUTILS_H

#include <ostream>
#include <string>
#include <vector>

#include <boost/filesystem.hpp>

#include "base/linearalgebra.h"
#include "base/resultset.h"

namespace insight
{

class OpenFOAMCase;

void initializeTurbulenceFields(
    OpenFOAMCase& cm,
    const boost::filesystem::path& dir );

void createCellZoneFromRegionSeedPoint(
    const OpenFOAMCase& cm,
    const boost::filesystem::path& dir,
    const std::string& zoneName,
    const arma::mat& PiM,
    const std::vector<std::string>& additionalSetCommands={}
    );

std::string getOpenFOAMComponentLabel(int i, int ncmpt);

void mergeMeshes(const OpenFOAMCase& targetcase, const boost::filesystem::path& source, const boost::filesystem::path& target);


void mapFields
(
  const OpenFOAMCase& targetcase,
  const boost::filesystem::path& source,
  const boost::filesystem::path& target,
  bool parallelTarget=false,
  const std::vector<std::string>& fields = std::vector<std::string>()
);

void resetMeshToLatestTimestep
(
    const OpenFOAMCase& c,
    const boost::filesystem::path& location,
    bool ignoremissing=false,
    bool include_zones=false,
    bool is_parallel=false
);

void runPotentialFoam(const OpenFOAMCase& cm, const boost::filesystem::path& location, int np=1);

void runPvPython
(
  const OpenFOAMCase& ofc,
  const boost::filesystem::path& location,
  const std::vector<std::string> pvpython_commands,
  bool keepScript = false
);

void currentNumericalSettingsReport(const OpenFOAMCase& cm,
               const boost::filesystem::path& location,
               ResultSet& results
		      );

arma::mat viscousForceProfile
(
  const OpenFOAMCase& cm,
  const boost::filesystem::path& location,
  const arma::mat& axis, int n,
    const std::vector<std::string>& addopts = {"-latestTime"}
);

void surfaceFeatureExtract
(
    const OpenFOAMCase& cm,
    const boost::filesystem::path& location,
    const std::string& surfaceName,
    double featureAngle = 60.
    );

/**
 * Converts a 3D mesh (e.g. generated by snappyHexMesh) into a 2D mesh
 * by just keeping the extrusion of a lateral patch
 * Assumptions:
 *  - X and Y directions are the 2D directions
 *  - mesh extent in Z direction is from 0 to some positive value
 *  - sourcePatchName is the patch lying in the XY plane
 *  - the 2D mesh is centered around the XY plane
 */
void extrude2DMesh
(
  const OpenFOAMCase& c,
  const boost::filesystem::path& location,
  const std::string& sourcePatchName,
  std::string sourcePatchName2="",
  bool wedgeInsteadOfPrism=false,
  double distance=1.0,
  const arma::mat& offsetTranslation=vec3(0,0,0.5),
  const arma::mat& fixedDirection = arma::mat()
);

/**
 * Rotates a lateral patch of a 3D mesh (e.g. generated by snappyHexMesh) into
 * a full 3D cylindrical mesh
 * Assumptions:
 *  - sourcePatchName is the patch lying in a coordinate plane
 */
void rotateMesh
(
  const OpenFOAMCase& c,
  const boost::filesystem::path& location,
  const std::string& sourcePatchName,
  int nc,
  const arma::mat& axis,
  const arma::mat& p0
);

arma::mat interiorPressureFluctuationProfile
(
  const OpenFOAMCase& cm,
  const boost::filesystem::path& location,
  const arma::mat& axis, int n,
    const std::vector<std::string>& addopts= {"-latestTime"}
);

std::vector<boost::filesystem::path> searchOFCasesBelow(const boost::filesystem::path& basepath);

void calcR
(
  const OpenFOAMCase& cm,
  const boost::filesystem::path& location,
    const std::vector<std::string>& addopts= {"-latestTime"}
);

void calcLambda2
(
  const OpenFOAMCase& cm,
  const boost::filesystem::path& location,
    const std::vector<std::string>& addopts= {"-latestTime"}
);

void VTKFieldToOpenFOAMField(const boost::filesystem::path& vtkfile, const std::string& fieldname, std::ostream& out);

class BoundingBox
    : public arma::mat
{
public:
  BoundingBox();
  void extend(const arma::mat& bb);

  void operator=(const arma::mat& bb);
};

}

#endif // INSIGHT_OFMISCUTILS_H
