/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011-2013 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Application
    surfaceTransformPoints

Description
    Transform (scale/rotate) a surface.
    Like transformPoints but for surfaces.

    The rollPitchYaw option takes three angles (degrees):
    - roll (rotation about x) followed by
    - pitch (rotation about y) followed by
    - yaw (rotation about z)

    The yawPitchRoll does yaw followed by pitch followed by roll.

\*---------------------------------------------------------------------------*/

#include "edgeMesh.H"
#include "argList.H"
#include "OFstream.H"
#include "IFstream.H"
#include "boundBox.H"
#include "transformField.H"
#include "Pair.H"
#include "quaternion.H"
#include "mathematicalConstants.H"

#include "uniof.h"

using namespace Foam;
// using namespace Foam::constant::mathematical;


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
    argList::noParallel();
    argList::validArgs.append("eMesh file");
    argList::validArgs.append("output VTK file");
    argList args(argc, argv);


    fileName inFileName(UNIOF_ADDARG(args,0));
    fileName outFileName(UNIOF_ADDARG(args,1));

    Info<< "Reading eMesh from " << inFileName << " ..." << nl
        << "Writing eMesh to " << outFileName << " ..." << endl;

#if defined(OF16ext)
    IFstream fi(inFileName);
    token headerKeyWord(fi);
    dictionary header(fi);
#endif

    edgeMesh edge1(inFileName);
    const pointField& pts = edge1.points();
    const edgeList& edgs = edge1.edges();

    OFstream vtk(outFileName);
    vtk
     <<"# vtk DataFile Version 2.0" << nl
     <<"generated by InsightCAE from "<<inFileName<<nl
     <<"ASCII"<<nl
     <<"DATASET POLYDATA" << nl
     <<"POINTS "<<pts.size()<<" float" << nl;
    forAll(pts, i)
    {
        const point& p=pts[i];
        vtk<<p.x()<<" "<<p.y()<<" "<<p.z()<<nl;
    }

    vtk<<"LINES "<<edgs.size()<<" "<<edgs.size()*3<<nl;
    forAll(edgs, i)
    {
        const edge& e=edgs[i];
        vtk<<"2 "<<e[0]<<" "<<e[1]<<nl;
    }

    Info<< "End\n" << endl;

    return 0;
}


// ************************************************************************* //
