#!/bin/bash

ARG_BRC=$1
shift 1
#ARGS=$*
SKIPPATTERN=$1
source $ARG_BRC
FIRST=1
if [ -d $WM_PROJECT_DIR/modules ]; then
 FOAM_MODULES=$WM_PROJECT_DIR/modules
fi
for bd in "$FOAM_SRC" "$FOAM_APP" $FOAM_MODULES; do
 for d in `find "$bd" -name "Make" -a -type d`; do 
  p="$(cd $d; cd ..; pwd)"
  SKIP=
  for skip in $SKIPPATTERN; do
   if [[ "$p" == *${skip} ]]; then SKIP=1; fi
  done
  if [ `basename $p` != "finiteArea" ] && [ ! "$SKIP" ]; then # skip this because of interfering header names, has to be included manually, if needed
   P="$p/lnInclude"
   if [ -d "$P" ]; then 
    if [ ! "$FIRST" ]; then echo -n ";"; else unset FIRST; fi
    echo -n "$P"
   fi
  fi
 done
done
