#!/bin/bash

ARG_BRC=$1
shift 1
#ARGS=$*
source $ARG_BRC
FIRST=1
for bd in "$FOAM_SRC" "$FOAM_APP"; do
 for d in `find "$bd" -name "Make" -a -type d`; do 
  P="$(cd $d; cd ..; pwd)/lnInclude"
  if [ -d "$P" ]; then 
   if [ ! "$FIRST" ]; then echo -n ";"; else unset FIRST; fi
   echo -n "$P"
  fi
 done
done